[RULESET.proxy]
name = "Proxy"
rules = [
    "DOMAIN-MATCH, google, PROXY",
    "DOMAIN-MATCH, gstatic, PROXY",
    "DOMAIN-MATCH, pokemon, PROXY",
    "DOMAIN-MATCH, tumblr, PROXY",
    "DOMAIN-MATCH, facebook, PROXY",
    "DOMAIN-MATCH, instagram, PROXY",
    "DOMAIN-MATCH, twimg, PROXY",
    "DOMAIN-MATCH, twitter, PROXY",
    "DOMAIN-MATCH, ifttt, PROXY"
]

